export type ActivityType = string &
  (
    // Job related
    | 'JOB_CREATED'
    | 'JOB_PUBLISHED'
    | 'JOB_UPDATED'
    | 'JOB_CLOSED'
    | 'JOB_PAUSED'
    | 'JOB_REACTIVATED'
    | 'JOB_DELETED'
    // Application related
    | 'APPLICATION_RECEIVED'
    | 'APPLICATION_REVIEWED'
    | 'APPLICATION_SHORTLISTED'
    | 'APPLICATION_REJECTED'
    | 'APPLICATION_STATUS_CHANGED'
    // Interview related
    | 'INTERVIEW_SCHEDULED'
    | 'INTERVIEW_COMPLETED'
    | 'INTERVIEW_CANCELLED'
    | 'INTERVIEW_RESCHEDULED'
    | 'INTERVIEW_STARTED'
    | 'INTERVIEW_FEEDBACK_SUBMITTED'
    | 'INTERVIEW_DELETED'
    | 'INTERVIEW_RESULT_SENT'
    // Candidate related
    | 'CANDIDATE_ADDED'
    | 'CANDIDATE_UPDATED'
    | 'CANDIDATE_DELETED'
    | 'CANDIDATE_HIRED'
    | 'CANDIDATE_REJECTED'
    | 'CANDIDATE_MOVED_TO_NEXT_STAGE'
    // System related
    | 'USER_LOGIN'
    | 'USER_LOGOUT'
    | 'USER_REGISTERED'
    | 'SETTINGS_UPDATED'
    | 'PROFILE_UPDATED'
    // Company related
    | 'COMPANY_CREATED'
    | 'COMPANY_UPDATED'
    | 'COMPANY_DELETED'
    | 'COMPANY_LOCATION_ADDED'
    | 'COMPANY_LOCATION_UPDATED'
    | 'COMPANY_LOCATION_DELETED'
    | 'TEAM_MEMBER_INVITED'
    | 'TEAM_MEMBER_UPDATED'
    | 'TEAM_MEMBER_DELETED'
    // AI related
    | 'AI_QUESTIONS_GENERATED'
    | 'AI_EVALUATION_COMPLETED'
    | 'AI_RESUME_ANALYZED'
  );
